= Simulators
:toc:

This repository contains proof-of-concept implementations of the RAST (introduced at https://doi.org/10.1109/MASCOTS56607.2022.00015[MASCOTS2022]) Simulator component for the following Systems Under Evaluation:

1. Alarm Receiving Software (ARS): ARS is a commercial software system from the GS company group. For more information, visit https://www.gselectronic.com[GS Electronic].
2. TeaStore: TeaStore is an open-source project hosted on GitHub. You can find the repository at https://github.com/DescartesResearch/TeaStore[TeaStore Repository].

[#how-to-start]
== How to Start the Simulator

To start the Simulator, follow these steps:

1. Navigate to your local Simulator folder.
2. Execute the command `./gradlew run -PmainClass=<simulator>` where <simulator> is the Simulator you want to start:
    * For ARS, use `-PmainClass=ArsKt`
    * For TeaStore, use `-PmainClass=TeastoreKt`
3. If the Simulator starts successfully, you will see the following line printed on the console: `INFO ktor.application - Responding at http://0.0.0.0:8081`.
4. To terminate the Simulator, press `Ctrl + C`.

Use `./gradlew run -PmainClass=<simulator> --args="--help"` to show optional CLI arguments.

== How to Adjust the Predictive Model

To adjust the predictive model for either the ARS or the TeaStore Simulator, follow these steps:

1. Locate the ordinal number of your desired model:
    * For ARS Simulator:
        ** Navigate to the `ars.kt` file.
        ** Locate the `ARSModelToUse` enum class showing the available models.
        ** Pass the ordinal number of the desired model as a CLI argument, like `./gradlew run -PmainClass=ArsKt --args="-m <ordinal_number>"`
    * For TeaStore Simulator:
        ** Navigate to the `teastore.kt` file.
        ** Locate the `TeaStoreModelToUse` enum class showing the available models.
        ** Pass the ordinal number of the desired model as a CLI argument, like `./gradlew run -PmainClass=TeastoreKt --args="-m <ordinal_number>"`

== How to Use a Custom Predictive Model

=== Quick Way (Override an Existing Model)

. Rename your model file (.pmml) and the request type mapping file (.json) to match an existing model. For example:
    * For a ridge regression model for the TeaStore simulator that uses PR 1, PR 2, and Request Type as predictor variables:
+
[source]
----
predictive_model_Ridge_09-12-2023_09:11:49.pmml
----
+
Rename to:
+
[source]
----
teastore_model_Ridge_T_PR_1_3.pmml
----

    * For a mapping file for the TeaStore simulator that uses ordinal encoding:
+
[source]
----
requests_mapping_09-12-2023_09:11:49.json
----
+
Rename to:
+
[source]
----
teastore_requests_mapping_LR_ordinal_encoding.json
----

. Copy the renamed model file and the request type mapping file to:
+
[source]
----
<your_local_simulators_folder>/src/main/resources
----
+
Overwrite the existing files. (Backup the old files if you like.)

== How to Adjust the Maximum Number of Corrections (corr_max)

The corr_max value (default 0) can be adjusted via the CLI:

`./gradlew run -PmainClass=<simulator> --args="-c <corr_max>"`

== How to implement a new Simulator

The Simulator consists of two main components: an API part that implements the system-specific API of your System Under Evaluation (SUE), and a Prediction part that implements our system-agnostic simulation. To create a new Simulator, you need to implement the API part and reuse the Prediction part.

We recommend using the Ktor library to implement the API module. You can refer to the `ars.kt` or `teastore.kt` files located in the `<your_local_simulators_folder>/src/main/kotlin` folder for examples of how to implement the API endpoints. The Prediction module is provided as a series of Ktor plugins, making integration straightforward with just a few lines of code:

.Minimal Ktor setup with the Prediction module installed
[source, kotlin]
----
// instantiate the plugin object and pass required parameters
val rastSimulationKtorPlugins = RASTSimulationKtorPlugins(prefix, urlsToIgnoreInPlugins, predictor)

val server = embeddedServer(
    Netty,
    host = "0.0.0.0",
    port = 1337,
) {
    // install all plugins
    rastSimulationKtorPlugins.installAllPlugins(this)

    routing {
        // definition of endpoints
    }
}.start(wait = false)
----

After having implemented the Simulator, you can use it by defining it in the `build.gradle.kts` file (see <<how-to-start>>).